# Generated by Django 3.2.15 on 2022-10-22 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postcomment_blog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostComment',
        ),
    ]
